### ISSUE TITLE
You're next for the exercise to contribute to ourfile.md (cannot find Fran)

### ISSUE THREAD

**Issue by rbstubbs** [cu-boulder/shared-skills-git#20]
@renaedahiya and @bradweiner  - how come I cannot find Fran's name when I do an at symbol in Git?

**Comment by bradweiner** [comment]
Good question. It's possible she never asked for access to this repo or doesn't have her account set up.

**Comment by renaedahiya** [comment]
@geoss - Rob has a pending status as a user to this repository and a question about Fran's access. Can we add Fran? I do not know what her git username is.

**Comment by renaedahiya** [comment]
@rbstubbs - Seth added ODA staff to this repo manually since it was configured as a public repository. He is the best person to recall the setup of Fran's access I would say.

**Comment by geoss** [comment]
Her username is @pba8633.

**Comment by geoss** [comment]
She may not have fully completed her profile or typed her handle as her name...

**Comment by rbstubbs** [comment]
that was going to be my second guess on her user ID.  thanks!
