### ISSUE TITLE
Github Desktop

### ISSUE THREAD

**Issue by geoss** [cu-boulder/shared-skills-git#3]
@anakatan had a hard time downloading the project using GitHub Desktop following my instructions to delete the http bits.  Try downloading leaving the URL intact if it doesn't work.

**Comment by geoss** [comment]
actually just see the items thread for the shared skills meeting.  I think we worked through the issues there...

**Comment by anakatan** [comment]
Thanks, yes, I saw them coming through over my phone while I was out. Will read through the thread and am sure I can figure it out from that. Have a nice night!

Sent from my iPhone

On Jan 4, 2021, at 5:14 PM, Seth Spielman <notifications@github.com> wrote:

﻿

actually just see the items thread for the shared skills meeting. I think we worked through the issues there...
