### ISSUE TITLE
Alex's turn on ourdoc

### ISSUE THREAD

**Issue by bradweiner** [cu-boulder/shared-skills-git#5]
Hi @aviggio. I think you're on deck for exercise #2. Might be useful to keep this ball rolling for folks who are already finished with exercise #1.

**Comment by aviggio** [comment]
Hi @bradweiner would you please review my pull request and merge if you approve of my change. Please also delete my branch per the instructions, as I understood them.

**Comment by aviggio** [comment]
Thanks @bradweiner appreciate your help. Closing this issue.
